### ISSUE TITLE
Build & deploy successful, bundle cannot start in AEM - some packages cannot be resolved

### ISSUE THREAD

**Issue by thesurenk** [AndreiShilov/sample-aem-kotlin-maven#1]
I see this on http://localhost:4502/system/console/bundles

`com.day.cq.dam.api,version=[1.23,2) -- Cannot be resolved
com.google.gson,version=[2.8,3) -- Cannot be resolved
kotlin -- Cannot be resolved
kotlin.jvm.internal -- Cannot be resolved
org.apache.sling.hc.api,version=[1.2,2) -- Cannot be resolved
org.apache.sling.hc.util,version=[1.5,2) -- Cannot be resolved`

<img width="1301" alt="screen shot 2018-04-16 at 9 07 37 pm" src="https://user-images.githubusercontent.com/902972/38844751-7f1461c0-41ba-11e8-811b-e07ae6f1681b.png">

**Comment by AndreiShilov** [comment]
Hi @ksurendra! Could you share your AEM version and java version

**Comment by thesurenk** [comment]
- AEM 6.3 with [Service Pack 1](https://helpx.adobe.com/experience-manager/6-3/release-notes/sp1-release-notes.html) and [CFP 6.3.1.2](https://helpx.adobe.com/experience-manager/release-notes--aem-6-3-cumulative-fix-pack.html)
- java version "1.8.0_162"
Java(TM) SE Runtime Environment (build 1.8.0_162-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.162-b12, mixed mode)

**Comment by AndreiShilov** [comment]
Currently I'm using uber jar for 6.4
`<dependency>
                <groupId>com.adobe.aem</groupId>
                <artifactId>uber-jar</artifactId>
                <version>6.4.0</version>
                <classifier>apis</classifier>
                <scope>provided</scope>
            </dependency>`

try to change it for AEM 6.3 sp1

**Comment by thesurenk** [comment]
Thanks.
Using [6.3.1.2](https://mvnrepository.com/artifact/com.adobe.aem/uber-jar/6.3.1.2) or 6.3.1.1 , build is failing. I'm trying to fix it..

`[ERROR] COMPILATION ERROR :` 
`[ERROR] /..../sample-aem-kotlin-maven-master/core/src/main/java/com/asd/aem/ktln/core/exporter/GsonExporter.java:[8,23] package com.google.gson does not exist`
`[ERROR] /..../sample-aem-kotlin-maven-master/core/src/main/java/com/asd/aem/ktln/core/exporter/GsonExporter.java:[22,24] cannot find symbol
`

**Comment by AndreiShilov** [comment]
@ksurendra  check out 6.2 branch https://github.com/AndreiShilov/sample-aem-kotlin-maven/commits/6.2

**Comment by thesurenk** [comment]
@AndreiShilov  With 6.2 branch, was able to resolve the gson issue. Still see these in the bundle..
`kotlin -- Cannot be resolved`
`kotlin.jvm.internal -- Cannot be resolved`

**Comment by AndreiShilov** [comment]
@ksurendra do you have up and running kotlin-osgi-bundle?

**Comment by thesurenk** [comment]
@AndreiShilov i do not see it in the bundles list

**Comment by AndreiShilov** [comment]
@ksurendra from what directory have you deployed project and with what command?

**Comment by thesurenk** [comment]
From 

`konathal-OSX:sample-aem-kotlin-maven-6.2 konathal$ pwd`
`/Users/konathal/kotlin-aem/6.2/sample-aem-kotlin-maven-6.2`
`konathal-OSX:sample-aem-kotlin-maven-6.2 konathal$ ls -la`
`drwxr-xr-x@ 10 konathal  staff    340 Apr 13 03:56 .`
`drwxr-xr-x   5 konathal  staff    170 Apr 17 11:31 ..`
`-rwxr-xr-x@  1 konathal  staff    977 Apr 13 03:56 .gitignore`
`-rwxr-xr-x@  1 konathal  staff   2423 Apr 13 03:56 README.md`
`drwxr-xr-x@  5 konathal  staff    170 Apr 17 11:32 core`
`drwxr-xr-x@  5 konathal  staff    170 Apr 17 11:32 it.launcher`
`drwxr-xr-x@  5 konathal  staff    170 Apr 17 11:32 it.tests`
`-rwxr-xr-x@  1 konathal  staff  26770 Apr 13 03:56 pom.xml`
`drwxr-xr-x@  5 konathal  staff    170 Apr 17 11:32 ui.apps`
`drwxr-xr-x@  5 konathal  staff    170 Apr 17 11:32 ui.content`

using `mvn clean install -PautoInstallBundle`

**Comment by AndreiShilov** [comment]
@ksurendra you should go with `mvn clean install -PautoInstallPackage` because `mvn clean install -PautoInstallBundle` installs only core bundle, but it depends on kotlin osgi bundle which one is embedded in ui.content submodule

Therefor try `mvn clean install -PautoInstallPackage` from the project root folder

**Comment by thesurenk** [comment]
Awesome it's active now. And you are right.. i should have checked the command.
